before_script:
    - ssh-keygen -F github.com || ssh-keyscan -H github.com >> ~/.ssh/known_hosts

variables:
    UPSTREAM_REPOSITORY: "git@github.com:bsc-pm/mcxx.git"
    UPSTREAM_BRANCH: "master"

mirror-master:
    stage: deploy
    only:
        - master
    script:
        - git remote add github $UPSTREAM_REPOSITORY || true
        - git fetch github
        - git push --follow-tags --set-upstream github $UPSTREAM_BRANCH
